stages:
  #- test
  - containerize
#- run_integration
variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
containerize.branch:
  image: docker:latest-git
  stage: containerize
  script:
    - echo $CONTAINER_TEST_IMAGE
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  except:
    - master
containerize.tag:
  image: docker:latest
  stage: containerize
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
    - tags